Admin/Models/Race/RaceCategory/RaceCategoriesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MujZavod.Admin.Models.Race.RaceCategory
{
    public class RaceCategoriesViewModel
    {
        public int RaceId { get; set; }
        public bool canEdit { get; set; }
        public List<RaceCategoryViewModel> RaceCategories {get;set;}
    }
}

Admin/Models/Race/RaceCategory/RaceRunners/RaceRunnerTimes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MujZavod.Admin.Models.Race.RaceCategory.RaceRunners
{
    public class RaceRunnerTimes
    {
        public int RaceRunnerId { get; set; }
        public List<RaceRunnersTimeRound> RaceRunnersTimeRounds { get; set; }

        public RaceRunnerTimes()
        {

        }

        public RaceRunnerTimes(Data.Models.RaceCategoryUser raceCategoryUser)
        {
            if (raceCategoryUser != null)
            {
                RaceRunnerId = raceCategoryUser.Id;
                RaceRunnersTimeRounds = raceCategoryUser.RaceCategory.RaceRounds.Select(x => new RaceRunnersTimeRound()
                {
                    RoundId = x.Id,
                    Name = x.Name,
                    Time = raceCategoryUser.RaceRoundUsers.FirstOrDefault(y=>y.RaceRoundId == x.Id)?.Time
                }).ToList();
            }
        }
    }

    public class RaceRunnersTimeRound
    {
        public int RoundId { get; set; }
        public string Name { get; set; }
        public TimeSpan? Time { get; set; }
    }
}

Admin/Controllers/RaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MujZavod.Admin.Helpers;
using MujZavod.Code.Extensions;


namespace MujZavod.Admin.Controllers
{
    public class RaceController : AccountController
    {
        private Code.Repository.RaceRepository _RaceRepository;
        private Code.Repository.RaceRepository RaceRepository => _RaceRepository ?? (_RaceRepository = new Code.Repository.RaceRepository());

        private Code.Repository.RaceCategoryRepository _RaceCategoryRepository;
        private Code.Repository.RaceCategoryRepository RaceCategoryRepository => _RaceCategoryRepository ?? (_RaceCategoryRepository = new Code.Repository.RaceCategoryRepository());

        private Code.Repository.EGenderRepository _EGenderRepository;
        private Code.Repository.EGenderRepository EGenderRepository => _EGenderRepository ?? (_EGenderRepository = new Code.Repository.EGenderRepository());

        private Code.Repository.RaceRoundRepository _RaceRoundRepository;
        private Code.Repository.RaceRoundRepository RaceRoundRepository => _RaceRoundRepository ?? (_RaceRoundRepository = new Code.Repository.RaceRoundRepository());

        private Code.Repository.ApplicationUserRepository _ApplicationUserRepository;
        private Code.Repository.ApplicationUserRepository ApplicationUserRepository => _ApplicationUserRepository ?? (_ApplicationUserRepository = new Code.Repository.ApplicationUserRepository());

        private Code.Repository.RaceSubCategoryRepository _RaceSubCategoryRepository;
        private Code.Repository.RaceSubCategoryRepository RaceSubCategoryRepository => _RaceSubCategoryRepository ?? (_RaceSubCategoryRepository = new Code.Repository.RaceSubCategoryRepository());

        private Code.Repository.RaceCategoryUsersRepository _RaceCategoryUsersRepository;
        private Code.Repository.RaceCategoryUsersRepository RaceCategoryUsersRepository => _RaceCategoryUsersRepository ?? (_RaceCategoryUsersRepository = new Code.Repository.RaceCategoryUsersRepository());

        // GET: Race
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GridData()
        {
            
            return Json(RaceRepository.GetAll().ToGridData(x=> new Models.Race.RaceGridRow(x)), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            Models.Race.RaceViewModel model;

            if (id.HasValue)
                model = new Models.Race.RaceViewModel(RaceRepository.GetById(id.Value));
            else
                model = new Models.Race.RaceViewModel();

            return PartialView(model);
        }


        [HttpPost]
        public ActionResult Edit(Models.Race.RaceViewModel model)
        {
            if (ModelState.IsValid)
            {
                Data.Models.Race race;

                if (!model.Id.HasValue)
                {
                    race = new Data.Models.Race();
                    race.OrganizerId = actUser.OrganizerId.Value;
                }
                else
                    race = RaceRepository.GetById(model.Id.Value);


                race.Name = model.Name;
                race.Description = model.RaceDescription;
                race.Date = model.Date.Value;
                race.SignToDate = model.SignToDate.Value;

                if (model.Id.HasValue)
                    RaceRepository.Update(race, true);
                else
                    RaceRepository.Create(race, true);

                return Content("OK");
            }
            return PartialView(model);
        }


        public ActionResult Detail(int id)
        {
            var race = RaceRepository.GetById(id);

            return View(new Models.Race.RaceDetailModel(race));
        }

        public ActionResult Head(int id)
        {
            
            return PartialView(new Models.Race.RaceViewModel(RaceRepository.GetById(id)));
        }

        

        [HttpGet]
        public ActionResult CategoryEdit(int? id, int raceId)
        {
            Models.Race.RaceCategory.RaceCategoryViewModel model;

            if (id.HasValue)
                model = new Models.Race.RaceCategory.RaceCategoryViewModel(RaceCategoryRepository.GetById(id.Value));
            else
                model = new Models.Race.RaceCategory.RaceCategoryViewModel() { RaceId = raceId };

            return PartialView("/Views/Race/Category/Edit.cshtml", model);
        }

        [HttpPost]
        public ActionResult CategoryEdit(Models.Race.RaceCategory.RaceCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                Data.Models.RaceCategory raceCategory;

                if (!model.Id.HasValue)
                {
                    raceCategory = new Data.Models.RaceCategory();
                    raceCategory.RaceId = model.RaceId;
                }
                else
                    raceCategory = RaceCategoryRepository.GetById(model.Id.Value);


                raceCategory.Name = model.Name;
                raceCategory.Description = model.Description;
                raceCategory.Start = model.Start.Value;
                
                if (model.Id.HasValue)
                    RaceCategoryRepository.Update(raceCategory, true);
                else
                    RaceCategoryRepository.Create(raceCategory, true);

                return Content("OK");
            }
            return PartialView("/Views/Race/Category/Edit.cshtml", model);
        }



        public ActionResult RoundGridData(int id)
        {
            return Json(RaceRoundRepository.GetAll().Where(x=>x.RaceCategoryId == id).ToGridData(x => new Models.Race.RaceCategory.Round.RoundGridRow(x)), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CategoryRoundEdit(int? id, int raceCategoryId)
        {
            Models.Race.RaceCategory.Round.RoundViewModel model;

            if (id.HasValue)
                model = new Models.Race.RaceCategory.Round.RoundViewModel(RaceRoundRepository.GetById(id.Value));
            else
                model = new Models.Race.RaceCategory.Round.RoundViewModel() { RaceCategoryId = raceCategoryId };

            return PartialView("/Views/Race/Category/Round/Edit.cshtml", model);
        }

        [HttpPost]
        public ActionResult CategoryRoundEdit(Models.Race.RaceCategory.Round.RoundViewModel model)
        {
            if (ModelState.IsValid)
            {
                Data.Models.RaceRound raceRound;

                if (!model.Id.HasValue)
                {
                    raceRound = new Data.Models.RaceRound();
                    raceRound.RaceCategoryId = model.RaceCategoryId;
                }
                else
                    raceRound = RaceRoundRepository.GetById(model.Id.Value);


                raceRound.Name = model.Name;
                raceRound.Distance = model.Distance;

                
                if (model.Id.HasValue)
                    RaceRoundRepository.Update(raceRound, true);
                else
                    RaceRoundRepository.Create(raceRound, true);

                return Content("OK");
            }
            return PartialView("/Views/Race/Category/Round/Edit.cshtml", model);
        }


        public ActionResult RaceRunnersGridData(int raceCategoryId)
        {
            return Json(RaceCategoryUsersRepository.getUsers(raceCategoryId)
                .ToGridData(x => new Models.Race.RaceCategory.RaceRunners.RaceRunnersGridRow(x)),
                JsonRequestBehavior.AllowGet);
        }


        public ActionResult SubCategoryGridData(int raceCategoryId)
        {
            return Json(RaceSubCategoryRepository.GetAll().Where(x=>x.RaceCategoryId == raceCategoryId)
                .ToGridData(x => new Models.Race.RaceCategory.SubCategory.SubCategoryGridRow(x)),
                JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult SubCategoryEdit(int? id, int raceCategoryId)
        {
            Models.Race.RaceCategory.SubCategory.SubCategoryViewModel model;

            if (id.HasValue)
                model = new Models.Race.RaceCategory.SubCategory.SubCategoryViewModel(RaceSubCategoryRepository.GetById(id.Value));
            else
                model = new Models.Race.RaceCategory.SubCategory.SubCategoryViewModel() { RaceCategoryId = raceCategoryId };

            return PartialView("/Views/Race/Category/SubCategory/Edit.cshtml", model);
        }

        [HttpPost]
        public ActionResult SubCategoryEdit(Models.Race.RaceCategory.SubCategory.SubCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                Data.Models.RaceSubCategory raceSubCategory;

                if (!model.Id.HasValue)
                {
                    raceSubCategory = new Data.Models.RaceSubCategory();
                    raceSubCategory.RaceCategoryId = model.RaceCategoryId;
                }
                else
                    raceSubCategory = RaceSubCategoryRepository.GetById(model.Id.Value);


                raceSubCategory.Name = model.Name;

                raceSubCategory.AgeFrom = model.AgeFrom;
                raceSubCategory.AgeTo = model.AgeTo;


                
                if (model.SelectedGenders != null)
                {
                    
                    var items = raceSubCategory.AllowedGenders.ToList();
                    foreach (var item in items)
                    {
                        if (!model.SelectedGenders.Contains(item.Id.ToString()))
                            raceSubCategory.AllowedGenders.Remove(item);
                    }

                    foreach (var item in model.SelectedGenders)
                    {
                        if (raceSubCategory.AllowedGenders.Count(x => x.Id == Convert.ToInt32(item)) == 0)

Admin/Controllers/RaceRegistrationController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using MujZavod.Data.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MujZavod.Admin.Controllers
{
    public class RaceRegistrationController : Controller
    {
        private Code.Repository.RaceRepository _RaceRepository;
        private Code.Repository.RaceRepository RaceRepository => _RaceRepository ?? (_RaceRepository = new Code.Repository.RaceRepository());

        private Code.Repository.ApplicationUserRepository _ApplicationUserRepository;
        private Code.Repository.ApplicationUserRepository ApplicationUserRepository => _ApplicationUserRepository ?? (_ApplicationUserRepository = new Code.Repository.ApplicationUserRepository());


        private Code.Repository.RaceCategoryRepository _RaceCategoryRepository;
        private Code.Repository.RaceCategoryRepository RaceCategoryRepository => _RaceCategoryRepository ?? (_RaceCategoryRepository = new Code.Repository.RaceCategoryRepository());

        private Code.Repository.RaceSubCategoryRepository _RaceSubCategoryRepository;
        private Code.Repository.RaceSubCategoryRepository RaceSubCategoryRepository => _RaceSubCategoryRepository ?? (_RaceSubCategoryRepository = new Code.Repository.RaceSubCategoryRepository());

        private Code.Repository.RaceCategoryUsersRepository _RaceCategoryUsersRepository;
        private Code.Repository.RaceCategoryUsersRepository RaceCategoryUsersRepository => _RaceCategoryUsersRepository ?? (_RaceCategoryUsersRepository = new Code.Repository.RaceCategoryUsersRepository());



        /// <summary>
        /// Povolení cross site .. budeme to vkládat někam..
        /// </summary>
        /// <param name="filterContext"></param>
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            filterContext.RequestContext.HttpContext.Response.AddHeader("Access-Control-Allow-Origin", "*");
            base.OnActionExecuting(filterContext);
        }



        
       
        
        public ActionResult Index(string Id, bool? iframe)
        {
            var race = RaceRepository.getRaceByKeyDetail(Id);
            return View(new Models.RaceRegistration.RaceRegistrationViewModel(race) { inIframe = iframe ?? false });
        }

        [HttpGet]
        public ActionResult RegisterOnRace(string raceKey)
        {
            var race = RaceRepository.getRaceByKey(raceKey);
            return PartialView(new Models.RaceRegistration.RegisterOnRaceViewModel(race));
        }

        [HttpPost]
        public ActionResult RegisterOnRace(Models.RaceRegistration.RegisterOnRaceViewModel model)
        {
            ApplicationUser au;
            if (model.RegistrationTypeId == 1)
            {
                au = UserManager.Find(model.EmailLogin, model.PasswordLogin);
            }
            else
            {
                au = new ApplicationUser
                {
                    
                    Email = model.Email,
                    EGenderId = model.EGenderId,
                    BirthDate = Convert.ToDateTime(model.BirthDate),
                    FirstName = model.FirstName,
                    LastName = model.SurName
                };

                if (model.CreateAccount)
                {
                    au.UserName = model.Email;
                    UserManager.Create(au, model.Password);
                    UserManager.SetLockoutEnabled(au.Id, false);
                    UserManager.AddToRole(au.Id, "User");
                }
                else
                {
                    au.UserName = Guid.NewGuid().ToString();
                    ApplicationUserRepository.Create(au, false);
                }
            }

            if (au != null)
            {
                Data.Models.RaceCategoryUser raceCategoryUser = new Data.Models.RaceCategoryUser()
                {
                    ApplicationUserId = au.Id,
                    RaceCategoryId = model.RaceCategoryId,
                    RaceSubCategoryId = model.RaceSubCategoryId
                };
                RaceCategoryUsersRepository.Create(raceCategoryUser, true);
            }

            return Content("OK");
        }

        public ActionResult CheckLogin(string email, string password)
        {
            var user = UserManager.Find(email, password);

            if (user != null)
                return Json(new { Success = true, User = new { EGenderId = user.EGenderId, BirthDate = user.BirthDate.ToString() } }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { Success = false, Err = "Nesprávné jméno/heslo" });
        }

        public ActionResult CheckFreeLogin(string email)
        {
            return Content(ApplicationUserRepository.isUsernameFree(email) ? "OK" : "Na daný email je již účet vytvořen.");
        }

        public ActionResult GetCategoryForUser(string raceKey, int genderId, string birthDate)
        {
            var categories = RaceCategoryRepository.GetCategoryForUser(raceKey, genderId, Convert.ToDateTime(birthDate));
            return Json( categories.Select(x => new { key= x.Id, value = x.Name }), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSubCategoryForUser(int genderId, string birthDate, int raceCategoryId)
        {
            var categories = RaceSubCategoryRepository.GetSubCategoryForUser(genderId, Convert.ToDateTime(birthDate), raceCategoryId);
            return Json(categories.Select(x => new { key = x.Id, value = x.Name }), JsonRequestBehavior.AllowGet);
        }



        


        public ActionResult RaceResults(string Id)
        {
            var race = RaceRepository.getRaceByKeyDetail(Id);
            return PartialView("~/Views/RaceRegistration/RaceResults.cshtml", new Models.RaceRegistration.RaceRegistrationViewModel(race));
        }




        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
    }
}

Admin/Views/Race/Detail.cshtml
@model MujZavod.Admin.Models.Race.RaceDetailModel

@{

    ViewBag.Title = "Detail závodu - " + Model.RaceViewModel.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section HeaderButtons{
    
}


<div id="raceHead">
    @Html.Partial("Head", Model.RaceViewModel)
</div>



<div id="raceCategories">
    @Html.Partial("Category/Categories", Model.RaceCategoriesViewModel)
</div>


@section head {

<script>
        var MujZavod = MujZavod || {};
        MujZavod.PublishRace = function () {
            bootbox.confirm({
                message: 'Přejete si zveřejnit závod? Po zveřejnění, nebudete moci závod editovat.',
                className: 'bootbox-xs',

                callback: function (result) {
                    if (result) {
                        $.get('@Url.Action("Publish", "Race", new { RaceId = Model.RaceViewModel.Id })', function (data) {
                            if (data == "OK") {
                                //$('#raceHead').load('@Url.Action("Head", "Race", new { id = Model.RaceViewModel.Id })');
                                location.reload();
                            }
                            else {
                                bootbox.alert({ message: data });
                            }
                        })
                    }
                },
            });
        }

        MujZavod.EndRace = function () {
            bootbox.confirm({
                message: 'Přejete si zveřejnit výsledky závodu?',
                className: 'bootbox-xs',

                callback: function (result) {
                    if (result) {
                        $.get('@Url.Action("EndRace", "Race", new { RaceId = Model.RaceViewModel.Id })', function (data) {
                            if (data == "OK") {
                                //$('#raceHead').load('@Url.Action("Head", "Race", new { id = Model.RaceViewModel.Id })');
                                location.reload();
                            }
                        })
                    }
                },
            });
        }

        MujZavod.RemoveRace = function () {
            MujZavod.Confirm('Opravdu si přejete smazat závod? O veškeré údaje přijdete.', function () {
                MujZavod.DoAction('@Url.Action("RemoveRace", "Race", new { id = Model.RaceViewModel.Id })', function () {
                    location.href = '@Url.Action("Index", "Race")';
                });
            });
        }
</script>

}

Admin/Views/Race/Edit.cshtml
@model MujZavod.Admin.Models.Race.RaceViewModel

@using (Html.BeginForm("Edit", "Race", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <span data-mz-modal-title="">@(Model.Id.HasValue ? "Úprava závodu" : "Vytvoření závodu")</span>

    @Html.ValidationSummary("", new { @class = "text-danger" })

    @Html.HiddenFor(x => x.Id)

    @Html.MzEditLineFor(x => x.Name)

    @Html.MzEditLineFor(x => x.Date)
    @Html.MzEditLineFor(x => x.SignToDate)

    @Html.LabelFor(x => x.RaceDescription)
    @Html.MzTextEditorFor(x => x.RaceDescription)
}

Admin/Views/Race/Head.cshtml
@model MujZavod.Admin.Models.Race.RaceViewModel

@{ 
    string webUrl = System.Web.Configuration.WebConfigurationManager.AppSettings.Get("webUrl");
}

<style>
    mz-code {
        white-space: pre-wrap;
        word-wrap: break-word;
        padding: 0px;
        margin: 0px;
    }


</style>

<div class="row">
    <div class="col-sm-12 col-lg-6">
        <div class="panel">
            <div class="panel-heading">
                <div class="panel-title">
                    Základní informace
@if (!Model.PublishDate.HasValue)
{
                    <span class="pull-right">
                        @Html.MzButton("Upravit", MzButton.MzButtonType.EDIT,
new { onclick = "new MujZavod.Modal('md').loadFromUrl('" + Url.Action("Edit", "Race", new { Id = Model.Id }) + "', function (raceModal) { raceModal.close(); $('#raceHead').load('" + Url.Action("Head", "Race", new { id = Model.Id }) + "'); });" }, "")

                        @Html.MzButton("Smazat", MzButton.MzButtonType.DELETE,
new { onclick = "MujZavod.RemoveRace(); return false;" }, "")
                    </span>
}
                </div>
            </div>
            <div class="panel-body form-horizontal">
                <div class="row">
                    <div class="col-sm-4">
                        @Html.LabelFor(x => x.Name)
                        <div>
                            @Html.Raw(Model.Name)
                        </div>
                        @*@Html.LabelValueRowFor(x => x.Name, 4, 8)*@
                    </div>
                    <div class="col-sm-4">
                        @Html.LabelFor(x => x.Date)
                        <div>
                            @Html.Raw(Model.Date)
                        </div>
                        @*@Html.LabelValueRowFor(x => x.Date, 4, 8)*@
                    </div>
                    <div class="col-sm-4">
                        @Html.LabelFor(x => x.SignToDate)
                        <div>
                            @Html.Raw(Model.SignToDate)
                        </div>
                        @*@Html.LabelValueRowFor(x => x.SignToDate, 4, 8)*@
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        @Html.LabelFor(x=>x.RaceDescription)
                        <div>
                            @Html.Raw(Model.RaceDescription)
                        </div>
                    </div>
                </div>
                
            </div>
        </div>

    </div>
    <div class="col-sm-12 col-lg-6">
        <div class="panel">
            <div class="panel-heading">
                <div class="panel-title">
                    Zveřejnění závodu
                    @if (!Model.PublishDate.HasValue)
                    {
                        @Html.MzButton("Zveřejnit závod", MzButton.MzButtonType.DEFAULT, 
                            new { onclick = "MujZavod.PublishRace(); return false;"  }, "pull-right btn-warning","fa fa-check-square")
                    }
                    else if (!Model.EndDtae.HasValue)
                    {
                        @Html.MzButton("Zveřejnit výsledky", MzButton.MzButtonType.DEFAULT, new { onclick = "MujZavod.EndRace(); return false;" }, "pull-right btn-warning", "fa fa-check-square")
                    }
                    else
                    {
                        @Html.MzButton("Zobrazit výsledky", MzButton.MzButtonType.DEFAULT, new { onclick = "var modalResults = new MujZavod.Modal('lg');  modalResults.loadFromUrl('" + Url.Action("RaceResults", "RaceRegistration", new { id = Model.RaceKey })+ "'); modalResults.setTitle('Výsledky závodu'); return false;" }, "pull-right", "fa fa-sort-numeric-asc")
                    }
                </div>
            </div>
            <div class="panel-body form-horizontal">
                @if (Model.PublishDate.HasValue)
                {
                    
                    @Html.LabelValueRowFor(x => x.PublishDate, 4, 8)

                    <h5>Možnosti přihlášení na závod:</h5>
                    <small>Na své stránky můžete vložit jednu z následujících forem přihlášení</small>

                    if (!Model.EndDtae.HasValue)
                    {
                    <div class="panel panel-transparent">
                        <div class="panel-heading"><div class="panel-title"><b>Kód pro vložení tlačítka na stránku</b></div></div>
                        Do sekce "head" vložte následující kód
                        <pre>
<xmp class="mz-code"><script src="@(webUrl)/Scripts/MujZavod/Registration"></script>
<link href="@(webUrl)/Content/MujZavod/Registration" rel="stylesheet" type="text/css">
<script>$(function () { new MujZavod.Registration({ wrapper: '#btnMujZavodRegister', url: '@(webUrl)', raceKey: '@Model.RaceKey' }); });</script></xmp></pre>

                        Kamkoliv na stránku vložte tlačítko <small>(případně ve scriptu upravte selector pro wrapper, na kterém se bude registrační průvodce volat)</small>
                        <pre><xmp><button id="btnMujZavodRegister">Přihlásit</button></xmp></pre>
                    </div>
                    }
                    <div class="panel panel-transparent">
                        <div class="panel-heading"><div class="panel-title"><b>Kód pro vložení detailu závodu na stránku</b></div></div>
                        <pre><xmp class="mz-code"><iframe width="100%" height="100%" src="@(webUrl)/RaceRegistration/Index/@(Model.RaceKey)?iframe=true" /></xmp></pre>
                    </div>

                    <div class="panel panel-transparent">
                        <div class="panel-heading"><div class="panel-title"><b>Odkaz na detail</b></div></div>
                        <pre><xmp class="mz-code">@(webUrl)/RaceRegistration/Index/@(Model.RaceKey)</xmp></pre>
                    </div>

                    

                    
                }
            </div>
        </div>
    </div>
</div>

Admin/Views/Race/Index.cshtml
@{
    ViewBag.Title = "Seznam závodů";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section HeaderButtons{
@Html.MzButton("Vytvořit závod", MzButton.MzButtonType.ADD, new { onclick="createRace();" }, "pull-right")
@*<button type="button" class="btn btn-primary pull-right" onclick="createRace();">Vytvořit</button>*@
}
<div>
    @Html.MzGrid(new MujZavod.Admin.Models.Race.RaceGridViewModel())
</div>






<script>
    function createRace() {
        var modalEdit = new MujZavod.Modal();
        modalEdit.loadFromUrl('@Url.Action("Edit","Race")', function () { MujZavod.Grids['GridRaces'].refresh(); modalEdit.close(); });

    }
</script>