Admin/Controllers/RaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MujZavod.Admin.Helpers;
using MujZavod.Code.Extensions;


namespace MujZavod.Admin.Controllers
{
    public class RaceController : AccountController
    {
        private Code.Repository.RaceRepository _RaceRepository;
        private Code.Repository.RaceRepository RaceRepository => _RaceRepository ?? (_RaceRepository = new Code.Repository.RaceRepository());

        private Code.Repository.RaceCategoryRepository _RaceCategoryRepository;
        private Code.Repository.RaceCategoryRepository RaceCategoryRepository => _RaceCategoryRepository ?? (_RaceCategoryRepository = new Code.Repository.RaceCategoryRepository());

        private Code.Repository.EGenderRepository _EGenderRepository;
        private Code.Repository.EGenderRepository EGenderRepository => _EGenderRepository ?? (_EGenderRepository = new Code.Repository.EGenderRepository());

        private Code.Repository.RaceRoundRepository _RaceRoundRepository;
        private Code.Repository.RaceRoundRepository RaceRoundRepository => _RaceRoundRepository ?? (_RaceRoundRepository = new Code.Repository.RaceRoundRepository());

        private Code.Repository.ApplicationUserRepository _ApplicationUserRepository;
        private Code.Repository.ApplicationUserRepository ApplicationUserRepository => _ApplicationUserRepository ?? (_ApplicationUserRepository = new Code.Repository.ApplicationUserRepository());

        private Code.Repository.RaceSubCategoryRepository _RaceSubCategoryRepository;
        private Code.Repository.RaceSubCategoryRepository RaceSubCategoryRepository => _RaceSubCategoryRepository ?? (_RaceSubCategoryRepository = new Code.Repository.RaceSubCategoryRepository());

        private Code.Repository.RaceCategoryUsersRepository _RaceCategoryUsersRepository;
        private Code.Repository.RaceCategoryUsersRepository RaceCategoryUsersRepository => _RaceCategoryUsersRepository ?? (_RaceCategoryUsersRepository = new Code.Repository.RaceCategoryUsersRepository());

        // GET: Race
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GridData()
        {
            
            return Json(RaceRepository.GetAll().ToGridData(x=> new Models.Race.RaceGridRow(x)), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            Models.Race.RaceViewModel model;

            if (id.HasValue)
                model = new Models.Race.RaceViewModel(RaceRepository.GetById(id.Value));
            else
                model = new Models.Race.RaceViewModel();

            return PartialView(model);
        }


        [HttpPost]
        public ActionResult Edit(Models.Race.RaceViewModel model)
        {
            if (ModelState.IsValid)
            {
                Data.Models.Race race;

                if (!model.Id.HasValue)
                {
                    race = new Data.Models.Race();
                    race.OrganizerId = actUser.OrganizerId.Value;
                }
                else
                    race = RaceRepository.GetById(model.Id.Value);


                race.Name = model.Name;
                race.Description = model.RaceDescription;
                race.Date = model.Date.Value;
                race.SignToDate = model.SignToDate.Value;

                if (model.Id.HasValue)
                    RaceRepository.Update(race, true);
                else
                    RaceRepository.Create(race, true);

                return Content("OK");
            }
            return PartialView(model);
        }


        public ActionResult Detail(int id)
        {
            var race = RaceRepository.GetById(id);

            return View(new Models.Race.RaceDetailModel(race));
        }

        public ActionResult Head(int id)
        {
            
            return PartialView(new Models.Race.RaceViewModel(RaceRepository.GetById(id)));
        }

        

        [HttpGet]
        public ActionResult CategoryEdit(int? id, int raceId)
        {
            Models.Race.RaceCategory.RaceCategoryViewModel model;

            if (id.HasValue)
                model = new Models.Race.RaceCategory.RaceCategoryViewModel(RaceCategoryRepository.GetById(id.Value));
            else
                model = new Models.Race.RaceCategory.RaceCategoryViewModel() { RaceId = raceId };

            return PartialView("/Views/Race/Category/Edit.cshtml", model);
        }

        [HttpPost]
        public ActionResult CategoryEdit(Models.Race.RaceCategory.RaceCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                Data.Models.RaceCategory raceCategory;

                if (!model.Id.HasValue)
                {
                    raceCategory = new Data.Models.RaceCategory();
                    raceCategory.RaceId = model.RaceId;
                }
                else
                    raceCategory = RaceCategoryRepository.GetById(model.Id.Value);


                raceCategory.Name = model.Name;
                raceCategory.Description = model.Description;
                raceCategory.Start = model.Start.Value;
                
                if (model.Id.HasValue)
                    RaceCategoryRepository.Update(raceCategory, true);
                else
                    RaceCategoryRepository.Create(raceCategory, true);

                return Content("OK");
            }
            return PartialView("/Views/Race/Category/Edit.cshtml", model);
        }



        public ActionResult RoundGridData(int id)
        {
            return Json(RaceRoundRepository.GetAll().Where(x=>x.RaceCategoryId == id).ToGridData(x => new Models.Race.RaceCategory.Round.RoundGridRow(x)), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CategoryRoundEdit(int? id, int raceCategoryId)
        {
            Models.Race.RaceCategory.Round.RoundViewModel model;

            if (id.HasValue)
                model = new Models.Race.RaceCategory.Round.RoundViewModel(RaceRoundRepository.GetById(id.Value));
            else
                model = new Models.Race.RaceCategory.Round.RoundViewModel() { RaceCategoryId = raceCategoryId };

            return PartialView("/Views/Race/Category/Round/Edit.cshtml", model);
        }

        [HttpPost]
        public ActionResult CategoryRoundEdit(Models.Race.RaceCategory.Round.RoundViewModel model)
        {
            if (ModelState.IsValid)
            {
                Data.Models.RaceRound raceRound;

                if (!model.Id.HasValue)
                {
                    raceRound = new Data.Models.RaceRound();
                    raceRound.RaceCategoryId = model.RaceCategoryId;
                }
                else
                    raceRound = RaceRoundRepository.GetById(model.Id.Value);


                raceRound.Name = model.Name;
                raceRound.Distance = model.Distance;

                
                if (model.Id.HasValue)
                    RaceRoundRepository.Update(raceRound, true);
                else
                    RaceRoundRepository.Create(raceRound, true);

                return Content("OK");
            }
            return PartialView("/Views/Race/Category/Round/Edit.cshtml", model);
        }


        public ActionResult RaceRunnersGridData(int raceCategoryId)
        {
            return Json(RaceCategoryUsersRepository.getUsers(raceCategoryId)
                .ToGridData(x => new Models.Race.RaceCategory.RaceRunners.RaceRunnersGridRow(x)),
                JsonRequestBehavior.AllowGet);
        }


        public ActionResult SubCategoryGridData(int raceCategoryId)
        {
            return Json(RaceSubCategoryRepository.GetAll().Where(x=>x.RaceCategoryId == raceCategoryId)
                .ToGridData(x => new Models.Race.RaceCategory.SubCategory.SubCategoryGridRow(x)),
                JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult SubCategoryEdit(int? id, int raceCategoryId)
        {
            Models.Race.RaceCategory.SubCategory.SubCategoryViewModel model;

            if (id.HasValue)
                model = new Models.Race.RaceCategory.SubCategory.SubCategoryViewModel(RaceSubCategoryRepository.GetById(id.Value));
            else
                model = new Models.Race.RaceCategory.SubCategory.SubCategoryViewModel() { RaceCategoryId = raceCategoryId };

            return PartialView("/Views/Race/Category/SubCategory/Edit.cshtml", model);
        }

        [HttpPost]
        public ActionResult SubCategoryEdit(Models.Race.RaceCategory.SubCategory.SubCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                Data.Models.RaceSubCategory raceSubCategory;

                if (!model.Id.HasValue)
                {
                    raceSubCategory = new Data.Models.RaceSubCategory();
                    raceSubCategory.RaceCategoryId = model.RaceCategoryId;
                }
                else
                    raceSubCategory = RaceSubCategoryRepository.GetById(model.Id.Value);


                raceSubCategory.Name = model.Name;

                raceSubCategory.AgeFrom = model.AgeFrom;
                raceSubCategory.AgeTo = model.AgeTo;


                
                if (model.SelectedGenders != null)
                {
                    
                    var items = raceSubCategory.AllowedGenders.ToList();
                    foreach (var item in items)
                    {
                        if (!model.SelectedGenders.Contains(item.Id.ToString()))
                            raceSubCategory.AllowedGenders.Remove(item);
                    }

                    foreach (var item in model.SelectedGenders)
                    {
                        if (raceSubCategory.AllowedGenders.Count(x => x.Id == Convert.ToInt32(item)) == 0)

Admin/Controllers/RunnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MujZavod.Code.Repository;

namespace MujZavod.Admin.Controllers
{
    

    public class RunnerController : Controller
    {

        RaceRepository _RaceRepository;
        RaceRepository RaceRepository => _RaceRepository ?? (_RaceRepository = new RaceRepository());

        RaceCategoryRepository _RaceCategoryRepository;
        RaceCategoryRepository RaceCategoryRepository => _RaceCategoryRepository ?? (_RaceCategoryRepository = new RaceCategoryRepository());

        RaceCategoryUsersRepository _RaceCategoryUsersRepository;
        RaceCategoryUsersRepository RaceCategoryUsersRepository => _RaceCategoryUsersRepository ?? (_RaceCategoryUsersRepository = new RaceCategoryUsersRepository());

        public ActionResult Index()
        {
            return View(new Models.Runner.RunnerRaceGridViewModel());
        }

        public ActionResult RunnerRacesGridData()
        {

            return Json(Helpers.GridHelper.ToGridData(
                RaceCategoryUsersRepository.GetAllByUser(
                    new ApplicationUserRepository().GetActAu().Id),
                    x=> new Models.Runner.RunnerRaceGridRow(x)
                ), JsonRequestBehavior.AllowGet);
        }
    }
}

Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <title>@ViewBag.title</title>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
    <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css">

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- Core stylesheets -->
    <link href="/content/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/content/css/pixeladmin.min.css" rel="stylesheet" type="text/css">
    <link href="/content/css/widgets.min.css" rel="stylesheet" type="text/css">
    <!-- Theme -->
    <link href="/content/css/themes/clean.min.css" rel="stylesheet" type="text/css">
    <!-- Pace.js -->
    <script src="/scripts/pace/pace.min.js"></script>
    @RenderSection("head", required: false)



    <!-- ==============================================================================
    |
    |  SCRIPTS
    |
    =============================================================================== -->
    <!-- Load jQuery -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Core scripts -->
    <script src="/scripts/js/bootstrap.min.js"></script>
    <script src="/scripts/js/pixeladmin.min.js"></script>
    
    <!-- Your scripts -->
    <script src="/scripts/js/app.js"></script>







    @Scripts.Render("~/Scripts/MujZavod/js")


    @RenderSection("scripts", required: false)

    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
    <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>

</head>
<body>
    @*
    <!-- Nav -->
    <nav class="px-nav px-nav-left">
        <button type="button" class="px-nav-toggle" data-toggle="px-nav">
            <span class="px-nav-toggle-arrow"></span>
            <span class="navbar-toggle-icon"></span>
            <span class="px-nav-toggle-label font-size-11">Sbalit menu</span>
        </button>
        <ul class="px-nav-content">
            <li class="px-nav-item active">
                <a href="@Url.Action("Index","Race")"><i class="px-nav-icon ion-home"></i><span class="px-nav-label">Seznam závodů</span></a>
            </li>

        </ul>
    </nav>
    *@
    <!-- Navbar -->
    <nav class="navbar px-navbar">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">MujZavod</a>
            </div>
       

      
           
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#px-navbar-collapse" aria-expanded="false"><i class="navbar-toggle-icon"></i></button>
            <div class="collapse navbar-collapse" id="px-navbar-collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Organizer"))
                    {
                    <li class="px-nav-item">
                        <a href="@Url.Action("Index", "Race")"><span class="px-nav-label">Seznam závodů</span></a>
                    </li>
                    }
                    @if (User.IsInRole("User"))
                    {
                    <li class="px-nav-item">
                        <a href="@Url.Action("Index", "Runner")"><span class="px-nav-label">Seznam závodů</span></a>
                    </li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            @User.Identity.Name
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Osobní údaje</a></li>
                            <li><a href="@Url.Action("ChangePassword","Account")">Změna hesla</a></li>
                            <li class="divider"></li>
                            <li>
                                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                            {
                                @Html.AntiForgeryToken()
                                <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-primary btn-block">
                                    <i class="pli-unlock icon-fw"></i> Odhlásit
                                </a>
                        }
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Content -->
    <div class="px-content container">
        <div class="page-header">
            <h1>@ViewBag.title</h1>
            <div class="pull-right">@RenderSection("HeaderButtons", required: false)</div>
        </div>
        <div class="">@RenderBody()</div>
    </div>
    <!-- Footer -->
    <footer class="px-footer px-footer-bottom container">
        Copyright © 2018 MujZavod.cz All rights reserved.
    </footer>
    
</body>
</html>

Admin/Views/Shared/_LayoutIframe.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_LayoutIframe</title>

    @Scripts.Render("~/Scripts/MujZavod/js")
</head>
<body>
    <div> 
        @RenderBody()
    </div>
</body>
</html>

Admin/Views/Shared/_LayoutPresentation.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <title>Můj závod</title>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
    <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css">
    <!-- Core stylesheets -->
    <link href="/content/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="/content/css/pixeladmin.min.css" rel="stylesheet" type="text/css">
    <link href="/content/css/widgets.min.css" rel="stylesheet" type="text/css">
    <!-- Theme -->
    <link href="/content/css/themes/clean.min.css" rel="stylesheet" type="text/css">
    <!-- Pace.js -->
    <script src="/scripts/pace/pace.min.js"></script>

    @RenderSection("head", required: false)
    <style>


        .account-container {
            width: auto;
            margin: 30px 10px;
        }

            .account-container form {
                border: 0;
                box-shadow: 0 2px 2px rgba(0,0,0,.05), 0 1px 0 rgba(0,0,0,.05);
            }

        @@media (min-width: 544px) {
            .account-container {
                width: 350px;
                margin: 60px auto;
            }
        }
    </style>
</head>
<body>
    <!-- ==============================================================================
    |
    |  SCRIPTS
    |
    =============================================================================== -->
    <!-- Load jQuery -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Core scripts -->
    <script src="/scripts/js/bootstrap.min.js"></script>
    <script src="/scripts/js/pixeladmin.min.js"></script>
    <!-- Your scripts -->
    <script src="/scripts/js/app.js"></script>

    @Scripts.Render("~/Scripts/MujZavod/js")

    @RenderSection("scripts", required: false)

    <!-- Content -->
    <div class="px-content">

        @RenderBody()
    </div>


</body>
</html>